blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Template Documentation
    url: https://github.com/stpnvkirill/dash-template#readme
    about: Please read the docs before creating an issue
  - name: ðŸ’¬ Discussions
    url: https://github.com/stpnvkirill/dash-template/discussions
    about: For questions about adapting the template to your project
